stages:
  - test

test:
  stage: test
  before_script:
    - cd docker
    - docker compose --env-file dev.env -f docker-compose.yml -f docker-compose.dev.yml up -d --build
    - cd ../tests
    - pip install -r requirements.txt
  script:
    - ./run_tests.py backend
  after_script:
    - cd docker
    - docker compose --env-file dev.env -f docker-compose.yml -f docker-compose.dev.yml down --volumes
