stages:
  - test

test:
  stage: test
  before_script:
    - cd docker
    - docker compose --env-file dev.env -f docker-compose.yml -f docker-compose.dev.yml up -d --build
    - cd ..
    - python3 -m venv tests/.venv
    - tests/.venv/bin/pip install -r tests/requirements.txt
  script:
    - cd tests
    - .venv/bin/python ./run_tests.py
  after_script:
    - cd docker
    - docker compose --env-file dev.env -f docker-compose.yml -f docker-compose.dev.yml down --volumes
